Added schema generation but with errors in tsc
include-davis/Include-CMS pull request #112
Opened 2024-07-16 00:41 UTC by brandonw504

2024-07-21 04:45 UTC, Austin2Shih requested changes
Just a few notes:
1) I expected to see a change to package.json/package-lock in this PR for the mongodb migrations library
2) I expect package.json changes to see the migration scripts such as 'npm run migrate:up/down`, `npm run setup`
3) To do the setup script you might want to make a script in the root level folder or make a folder named scripts somewhere and run scripts from there. Just make sure you consider both windows and linux.
4) I also expect to see some migrations in here in some sort of migrations folder

2024-07-21 04:45 UTC, Austin2Shih commented on app/(api)/_schema/generateTypes.ts
probably thinking that the type generation would be sort of an `npm run init` or `npm run setup` type of situation where it will generate a migration for us from the schema. Maybe it can just be that if we run `npm run setup`, a new migration file is made for us defining all these collections for our db

2024-07-21 04:45 UTC, Austin2Shih commented on app/(api)/_schema/index.mjs
like i mentioned sometime before, maybe we don't need schema anymore. We can probably just get rid of all of the _schema folder and have the schema defined in db migrations which would be set up in the npm run setup script

2024-07-29 00:12 UTC, brandonw504 commented
Gonna be getting rid of _schema soon, and I'll have to figure out something for the types migration generating script. I'm wondering whether it would be okay to change the files in _configs to .mjs files, since it seems I ought to be using a .mjs in _utils/mongodb (may experiment with .mts first).

2024-07-30 05:50 UTC, brandonw504 commented
I made some changes to the types files, switching from .ts to .mjs (I haven't deleted the .ts ones yet in case). Would it be okay to fully make the switch? I switched over since my setup script should (I think) be an ES module.

Also, about migrations, since we're using migrate-mongo, it has its own commands, but I can map them to something custom in package.json if you'd like.

2024-07-30 23:17 UTC, brandonw504 commented
So ultimately I ended up keeping _schema, and just generating the JSON schema validation, which I then use in the migration.

2024-08-18 05:59 UTC, brandonw504 commented
My goal with the types migration was to keep the (api)/_schema directory and automatically generate the schema for the types into it. It's not necessary so we can decide whatever if we want to only keep the JSON schemas in the migration files directly (since we probably won't need the schemas for anything else). I'm also generating the migrations automatically when you run `npm run setup`.

However, I'm not really sure how to integrate the schema in _configs/_schema since they're .ts files. I tried a couple things like having our project use ESM by default and changing other things to .ts, but I couldn't find a solution. For now, I replaced the .ts files with .mjs in _configs/_schema to make it work, but it causes problems in other places that expect Typescript files. I'll keep looking for a way to fix this.

2024-12-23 08:21 UTC, closed without merging