feat/selectbutton
include-davis/Include-CMS pull request #43
Opened 2024-03-08 05:34 UTC by foramms

Added the selectbutton.tsx file in components, selectmodecontext.tsx file in context and useselectmode.ts in hooks

I also edited pages and hero.tsx so that the selectmodecontext provider was imported there.

2024-03-10 04:10 UTC, foramms commented
![Uploading Screenshot 2024-03-09 at 8.10.20 PM.png…]()

2024-04-01 02:09 UTC, Austin2Shih requested changes
Overall looks great! Just a few things that I'm not sure if we need to change that are mentioned in the comments

2024-04-01 02:09 UTC, Austin2Shih commented on package.json
> +    "dotenv": "^16.4.5",
Is it possible to not have to change the package.json? I believe env files should be loaded automatically by next.js. Let me know if you have trouble getting it to work without dotenv

2024-04-01 02:09 UTC, Austin2Shih commented on app/(pages)/(index-page)/page.tsx
> +import React from 'react';
Not sure if this is neccesary

2024-04-01 02:09 UTC, Austin2Shih commented on app/(pages)/_components/SelectButton.tsx
> +  const buttonStyle = {
i like how this keeps things clean and out of the way of the actual html :)

2024-04-10 01:03 UTC, foramms commented
@Austin2Shih made the changes as suggested! thank you sm!

2024-04-17 02:56 UTC, Austin2Shih requested changes
Good work! Just a few changes requested

2024-04-17 02:56 UTC, Austin2Shih commented on app/(pages)/_components/SelectButton.tsx
> +  const [isSelected, setIsSelected] = useState(false);
I think the isSelected and setIsSelected can be part of the useSelectMode context. This means you can just say something like:

`const { selectMode, toggleSelectMode } = useSelectMode();`

This way lines 5 and 6 can be replaced with one line and all future components using the context don't have to write extra code :).

2024-04-17 02:56 UTC, Austin2Shih commented on app/(pages)/_contexts/SelectModeContext.tsx
> +const SelectModeContext = createContext<SelectModeContextType | undefined>(
Rather than undefined, maybe just input some default value that fits the SelectModeContextType interface. If this is not possible, then this is fine.

2024-04-17 02:56 UTC, Austin2Shih commented on app/(pages)/_contexts/SelectModeContext.tsx
> +export const useSelectMode = () => {
define this in the _hooks folder, you can remove this from the context provider file

2024-04-24 01:20 UTC, Austin2Shih requested changes
just a few changes

2024-04-24 01:20 UTC, Austin2Shih commented on package-lock.json
> +    "node_modules/dotenv": {
don't change package lock either

2024-04-24 01:20 UTC, Austin2Shih commented on package-lock.json
> +        "dotenv": "^16.4.5",
don't change package.json

2024-04-28 16:33 UTC, foramms commented
@Austin2Shih made the changes as suggested! pls review again, ty! :)

2024-05-02 06:47 UTC, Austin2Shih requested changes
Sooooo close! Also remember to get rid of the package.json changes. the jsonwebtoken package should definitely not be removed and we don't want to add dotenv. You probably wanna revert the package.json to an old state and then just run npm install to get all the packages.

2024-05-02 06:47 UTC, Austin2Shih commented on app/(pages)/(index-page)/_components/Hero/Hero.tsx
> +import { SelectModeContextProvider } from '../../../_hooks/SelectModeContext';
use the @hooks shortcut

2024-05-02 06:47 UTC, Austin2Shih commented on app/(pages)/(index-page)/_components/Hero/Hero.tsx
> +import React from 'react';
remove this

2024-05-02 06:47 UTC, Austin2Shih commented on app/(pages)/_components/SelectButton.tsx
> +  const handleClick = () => {
if all handleClick does is call another function, then you can just write the function in the onClick

2024-05-02 06:47 UTC, Austin2Shih commented on app/(pages)/_components/SelectButton.tsx
> +      <button style={buttonStyle} onClick={handleClick}>
just write onClick={toggleSelectMode}

2024-05-09 17:28 UTC, Austin2Shih approved these changes
YUHHHH

2024-05-09 17:29 UTC, merged